services:
  fora:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: fora
    restart: unless-stopped
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_POST_MAX_SIZE: 50M
      PHP_UPLOAD_MAX_FILESIZE: 100M
      php.opcache.enable_cli: 1
      php.variables_order: EGPCS
      SERVICE_NGINX_CLIENT_MAX_BODY_SIZE: 100M
      PHP_IDE_CONFIG: 'serverName=fora.loc'
      XDEBUG_MODE: develop,debug,coverage
      XDEBUG_START_WITH_REQUEST: yes
      XDEBUG_CLIENT_HOST: docker.for.mac.localhost
      XDEBUG_CLIENT_PORT: 9003
      XDEBUG_OUTPUT_DIR: /var/log
      XDEBUG_IDE_KEY: INTELLIJ-IDEA
    ports:
      - '${FORWARD_HTTP_PORT:-80}:80'
      - '${FORWARD_HTTPS_PORT:-443}:443'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - fora-network
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0.33
    container_name: fora-mysql
    restart: unless-stopped
    command:
      - "mysqld"
      - "--skip-log-bin" #This option disables binary logging, it eats up space locally without need.
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'fora-mysql:/var/lib/mysql'
    networks:
      - fora-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-pmysqlpasswdroot" ]
      retries: 3
      timeout: 5s

  redis:
    image: redis
    container_name: fora-redis
    restart: unless-stopped
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - fora-network
    volumes:
      - 'fora-redis:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

networks:
  fora-network:
    driver: bridge

volumes:
  fora-mysql:
    driver: local
  fora-redis:
    driver: local
