version: '3'
services:
  booking-engine:
    build:
      context: .
      dockerfile: infrastructure/docker/php-8.2/Dockerfile
    image: booking-engine:latest
    container_name: booking-engine
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: fora
      DB_USERNAME: admin
      DB_PASSWORD: mysqlsecretpasswd
      REDIS_HOST: redis
    ports:
      - "8080:80"
    networks:
      - travelagentadmin-network

  redis:
    image: redis
    container_name: booking-engine-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - travelagentadmin-network

  mysql:
    image: mysql:8.0.33
    container_name: booking-engine-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fora
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysqlsecretpasswd
      MYSQL_ROOT_PASSWORD: mysqlpasswdroot
    networks:
      - travelagentadmin-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: booking-engine-phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - travelagentadmin-network

networks:
  travelagentadmin-network:
    driver: bridge
