name: Laravel
on:
  push:
    branches: ["master", "dev", "stage-ndr"]
  pull_request:
    branches: ["master", "dev", "stage-ndr"]

jobs:
  laravel-phpunit:
    runs-on: ubuntu-latest

    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    env:
      DB_ROOT_USER: root
      DB_ROOT_PASSWORD: mysqlpasswdroot
      DB_DATABASE_HOST: mysql
      DB_DATABASE: tests_obe
      SUPPLIER_CONTENT_DB_DATABASE: tests_obe_content
      DB_DATABASE_USER: admin
      BOOKING_SUPPLIER_HBSI_USERNAME: ${{ secrets.BOOKING_SUPPLIER_HBSI_USERNAME }}
      BOOKING_SUPPLIER_HBSI_PASSWORD: ${{ secrets.BOOKING_SUPPLIER_HBSI_PASSWORD }}
      BOOKING_SUPPLIER_HBSI_CHANNEL_IDENTIFIER_ID: ${{ secrets.BOOKING_SUPPLIER_HBSI_CHANNEL_IDENTIFIER_ID }}
      BOOKING_SUPPLIER_HBSI_SEARCH_BOOK_URL: ${{ secrets.BOOKING_SUPPLIER_HBSI_SEARCH_BOOK_URL }}
      BOOKING_SUPPLIER_HBSI_COMPONENT_INFO_ID: ${{ secrets.BOOKING_SUPPLIER_HBSI_COMPONENT_INFO_ID }}
      BOOKING_SUPPLIER_HBSI_TARGET: ${{ secrets.BOOKING_SUPPLIER_HBSI_TARGET }}
      SUPPLIER_EXPEDIA_API_KEY: ${{ secrets.SUPPLIER_EXPEDIA_API_KEY }}
      SUPPLIER_EXPEDIA_SHARED_SECRET: ${{ secrets.SUPPLIER_EXPEDIA_SHARED_SECRET }}
      SUPPLIER_EXPEDIA_BASE_URL: ${{ secrets.SUPPLIER_EXPEDIA_BASE_URL }}
      SUPPLIER_ICE_PORTAL_CLIENT_ID: ${{ secrets.SUPPLIER_ICE_PORTAL_CLIENT_ID }}
      SUPPLIER_ICE_PORTAL_CLIENT_SECRET: ${{ secrets.SUPPLIER_ICE_PORTAL_CLIENT_SECRET }}
      SUPPLIER_ICE_PORTAL_BASE_URL: ${{ secrets.SUPPLIER_ICE_PORTAL_BASE_URL }}
      SUPPLIER_ICE_PORTAL_TOKEN_URL: ${{ secrets.SUPPLIER_ICE_PORTAL_TOKEN_URL }}
      SUPPLIER_EXPEDIA_RATE_TYPE: ${{ secrets.SUPPLIER_EXPEDIA_RATE_TYPE }}

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: mysqlpasswdroot
          MYSQL_USER: admin
          MYSQL_PASSWORD: mysqlsecretpasswd
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install Composer Dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Install additional PHP extensions
        run: |
          apt-get update
          apt-get install -y php8.2-xdebug
          echo "xdebug.mode=develop,debug,coverage" | tee -a /etc/php/8.2/cli/php.ini
          php -v

      - name: Create Databases And Grant All Privileges
        run: |
          mysql -u ${{ env.DB_ROOT_USER }} -p${{ env.DB_ROOT_PASSWORD }} -h ${{ env.DB_DATABASE_HOST }} -e "CREATE DATABASE IF NOT EXISTS ${{ env.DB_DATABASE }};"
          mysql -u ${{ env.DB_ROOT_USER }} -p${{ env.DB_ROOT_PASSWORD }} -h ${{ env.DB_DATABASE_HOST }} -e "CREATE DATABASE IF NOT EXISTS ${{ env.SUPPLIER_CONTENT_DB_DATABASE }};"
          mysql -u ${{ env.DB_ROOT_USER }} -p${{ env.DB_ROOT_PASSWORD }} -h ${{ env.DB_DATABASE_HOST }} -e "GRANT ALL PRIVILEGES ON ${{ env.DB_DATABASE }}.* TO '${{ env.DB_DATABASE_USER }}'@'%';"
          mysql -u ${{ env.DB_ROOT_USER }} -p${{ env.DB_ROOT_PASSWORD }} -h ${{ env.DB_DATABASE_HOST }} -e "GRANT ALL PRIVILEGES ON ${{ env.SUPPLIER_CONTENT_DB_DATABASE }}.* TO '${{ env.DB_DATABASE_USER }}'@'%';"
          mysql -u ${{ env.DB_ROOT_USER }} -p${{ env.DB_ROOT_PASSWORD }} -h ${{ env.DB_DATABASE_HOST }} -e "FLUSH PRIVILEGES;"

      - name: Run Database Migrations With Seeding
        run: php artisan migrate --seed

      - name: Install Node Modules And Build Frontend
        run: |
          npm i
          npm run build --if-present

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run PHPUnit/Feature Tests with Coverage
        run: php artisan test --coverage --min=75
