name: Laravel
on:
  push:
    branches: ["master", "dev", "new_general_github_workflow_mysql"]
  pull_request:
    branches: ["master", "dev", "new_general_github_workflow_mysql"]

jobs:
  laravel-phpunit:
    runs-on: ubuntu-latest

    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: mysqlpasswdroot
          MYSQL_USER: admin
          MYSQL_PASSWORD: mysqlsecretpasswd
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install Composer Dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Create Databases And Grant All Privileges
        run: |
          mysql -uroot -p${{ env.DB_ROOT_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ env.DB_DATABASE }};"
          mysql -uroot -p${{ env.DB_ROOT_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ env.SECOND_DB_DATABASE }};"
          mysql -uroot -p${{ env.DB_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON ${{ env.DB_DATABASE }}.* TO '${{ env.DB_USERNAME }}'@'%';"
          mysql -uroot -p${{ env.DB_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON ${{ env.SECOND_DB_DATABASE }}.* TO '${{ env.SECOND_DB_USERNAME }}'@'%';"
          mysql -uroot -p${{ env.DB_ROOT_PASSWORD }} -e "FLUSH PRIVILEGES;"

      - name: Run Database Migrations With Seeding
        run: php artisan migrate --seed

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run PHPUnit/Feature Tests with Coverage
        run: php artisan test --coverage --min=80
