name: Laravel

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x"]
        php-version: ["8.2"]

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: ${{ matrix.php-version }}

      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Set up MySQL
        uses: actions/setup-mysql@v1
        with:
          mysql-version: '5.7'

      - name: Create Database
        run: |
          mysql -u ${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_PASSWORD }} -e "CREATE DATABASE laravel_db;"
          mysql -u ${{ secrets.MYSQL_USERNAME }} -p${{ secrets.MYSQL_PASSWORD }} -e "CREATE DATABASE laravel_db2;"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present

      - name: Run PHPUnit Tests with Coverage
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel_db
          DB_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          SECOND_DB_HOST: 127.0.0.1
          SECOND_DB_PORT: 3306
          SECOND_DB_DATABASE: laravel_db2
          SECOND_DB_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          SECOND_DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: php artisan test --coverage --min=75
