name: Laravel

on:
  push:
    branches: ["master", "dev", "new_general_github_workflow_mysql"]
  pull_request:
    branches: ["master", "dev", "new_general_github_workflow_mysql"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x"]
        php-version: ["8.2"]

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: mysqlpasswdroot
          MYSQL_USER: admin
          MYSQL_PASSWORD: mysqlsecretpasswd
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: ${{ matrix.php-version }}

      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install

      - name: Create Database and User
        run: |
          mysql -u root -pmysqlpasswdroot -e "CREATE DATABASE IF NOT EXISTS ujv;"
          mysql -u root -pmysqlpasswdroot -e "CREATE DATABASE IF NOT EXISTS ujv_api;"
          mysql -u root -pmysqlpasswdroot -e "GRANT ALL PRIVILEGES ON ujv.* TO 'admin'@'%';"
          mysql -u root -pmysqlpasswdroot -e "GRANT ALL PRIVILEGES ON ujv_api.* TO 'admin'@'%';"
          mysql -u root -pmysqlpasswdroot -e "FLUSH PRIVILEGES;"

      - name: Generate key
        run: php artisan key:generate

      - name: Run Database Migrations With Seeding
        run: php artisan migrate --seed

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present

      - name: Run PHPUnit/Feature Tests with Coverage
        env:
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_PORT: 3306
          DB_DATABASE: ujv
          DB_USERNAME: admin
          DB_PASSWORD: mysqlsecretpasswd

          DB_CONNECTION_2: mysql2
          SECOND_DB_HOST: mysql
          SECOND_DB_PORT: 3306
          SECOND_DB_DATABASE: ujv_api
          SECOND_DB_USERNAME: admin
          SECOND_DB_PASSWORD: mysqlsecretpasswd
        run: php artisan test --coverage --min=80
